language: python
dist: bionic
install:
- pip install -e .[test] tox
matrix:
  include:
    - python: 3.6
      env: TOXENV=lint,py36
    - python: 2.7
      env: TOXENV=py27
script:
- tox
deploy:
  provider: pypi
  user: planet
  password:
    secure: t4zk4BO4G9/ph5lpspGwTPdLJgVAacge613aR9luoqaofqN+9EBlNouuuj+Fs3tOKA336RiNO508Xg+pjdT1aXJ9sSnELA/MJuN/bxs2f+lcne7GvJILBODKr0CFASs+0Ta0wELq4Aa+lVPxSK7j32TrWyTrzrojT2j3/zyKZ77sfM4kbDwbFWoNQYdOvaJb/ab+snKjTQLfqbjP33I+Ylt8LePi5/GpfK0ROriN7wgkIBXWepRIqlgnkXKIYbhAvwlEPbvnNC9FTQ2yqQFhicHR5XCE4zoF/2DbQc8SRddNaxKI6slqbNX+Zx84zbLwzTUIhsyO2mezrXZLnTFc+TU4ikCUNZ6qCJdaRoOGq3WO1V0FdtPqQobJpPtBHbjon4z2nECXPXdCYNiP6chBWP9Ck2fLeoSX9qP9Cf+5d7cexZ9hwfEtEEI0KHz3W8OjiwWOZNUbb66zWMJqNQ1K7D1smZgCnoNMKvJsdBbdLVs3XGsEj8u5uqSbHSFa9d7QVBqUFvpzl4h287G5pkpLShI1JhwH9/yeQHA6lD475rQ7TLYCscDpNU5i6eoyLVT4jvC9OQmCOjyN70yvm9u1JxYs6ihXU/tRVZY8TkXBsmAYibcWCOacm4/eglmXxNB7Lj1nuv22/s7ydPbhQ82Ed4P9C3shS6tQ68BkzP8cRrs=
  on:
    tags: true
    repo: planetlabs/cosmolog
